apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-monitor-development
spec:
  selector:
    matchLabels:
      app: status-dashboard-development
  endpoints:
  - port: https
    interval: 30s
